// This file is auto-generated from CSV files in convex/data/
// Do not edit this file directly. Edit the CSV files instead.
// Run 'pnpm generate:question-sets' to regenerate this file.

function parseCSV(csvText: string): Array<{
  category: string;
  text: string;
  answer: string;
  points: number;
}> {
  const lines = csvText.trim().split("\n");
  const questions = [];

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    // Simple CSV parser - handles quoted fields
    const values: string[] = [];
    let current = "";
    let inQuotes = false;

    for (let j = 0; j < line.length; j++) {
      const char = line[j];
      if (char === '"') {
        inQuotes = !inQuotes;
      } else if (char === "," && !inQuotes) {
        values.push(current.trim());
        current = "";
      } else {
        current += char;
      }
    }
    values.push(current.trim());

    if (values.length >= 4) {
      questions.push({
        category: values[0],
        text: values[1],
        answer: values[2],
        points: parseInt(values[3], 10),
      });
    }
  }

  return questions;
}

const JULEBORD_CSV = `category,text,answer,points
Fotball VM,Hvilket land har vunnet VM flest ganger?,Brasil,100
Fotball VM,Hvor skal Norge spille kampene sine i VM?,"Boston, New York",200
Fotball VM,"Hvem har rekorden for flest mål i VM noensinne?",Miroslav Klose,300
Fotball VM,Hvilke 3 lag har aldri tapt en VM finale?,"Spania, England, Uruguay",400
Fotball VM,Nevn alle målscorere i finalen i 2018,"Mandzukic, Griezmann, Pogba, Mbappe og Perisic",500
Jul,Hvilken dag er kjent som ""Boxing Day""?,2. juledag (26. desember),100
Jul,Hvilket dyr er det hovmesteren snubler i?,Tiger,200
Jul,"Hvem spiller ""The Grinch""",Jim Carrey,300
Jul,Hva er hovedingrediensen i kransekake?,Mandler,400
Jul,Hvorfor fant man på å stikke nellikspiker inn i en appelsin?,For å holde pesten unna,500
Alkohol,Hvilken drikke skal vi fram til?,Fireball,100
Alkohol,Hvilken drikke skal vi fram til?,Smirnoff Ice,200
Alkohol,Hvilken drikke skal vi fram til?,Øl,300
Alkohol,Hvilken drikke skal vi fram til?,Guiness,400
Alkohol,Hvilken drikke skal vi fram til?,"Vodka Martini, shaken not stirred",500
Geografi,Hva er hovedstaden i Nederland?,Amsterdam,100
Geografi,Hvor mange fylker har vi i Norge? ,15,200
Geografi,Nevn 3 byer/stater som har Disneyland,"Paris, California, Orlando, Tokyo, Hong Kong og Shanghai",300
Geografi,Hvilke land grenser Polen til? (5/7),"Tyskland, Tsjekkia, Slovakia, Ukarina, Belarus, Litauen og Russland",400
Geografi,Hvor lang er Glomma?,623km,500
Diverse,Hvilke farger trenger man for å lage grønn?,Blå og gul,100
Diverse,Hvem er den mest streamede artisten på Spotify i 2025?,Bad Bunny,200
Diverse,Hva er power splitten på de nye motorene i F1?,50/50,300
Diverse,Hva trenger du for å crafte en kake i minecraft?,"3 melk, 3 hvete, 2 sukker og ett egg",400
Diverse,Hvilke rammeverk har jeg laget denne appen i?,Next,500`;

export const QUESTION_SETS = [
  {
    id: "julebord",
    name: "Julebord Set",
    description: "Norwegian Christmas party questions",
    questions: parseCSV(JULEBORD_CSV),
  },
];