#!/usr/bin/env node
/**
 * Build script to generate questionSets.ts from CSV files
 * Run this script whenever CSV files are updated
 */

import * as fs from "fs";
import * as path from "path";

function parseCSV(csvText: string): Array<{
  category: string;
  text: string;
  answer: string;
  points: number;
}> {
  const lines = csvText.trim().split("\n");
  const questions = [];

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    // Simple CSV parser - handles quoted fields
    const values: string[] = [];
    let current = "";
    let inQuotes = false;

    for (let j = 0; j < line.length; j++) {
      const char = line[j];
      if (char === '"') {
        inQuotes = !inQuotes;
      } else if (char === "," && !inQuotes) {
        values.push(current.trim());
        current = "";
      } else {
        current += char;
      }
    }
    values.push(current.trim());

    if (values.length >= 4) {
      questions.push({
        category: values[0],
        text: values[1],
        answer: values[2],
        points: parseInt(values[3], 10),
      });
    }
  }

  return questions;
}

const dataDir = path.join(__dirname, "..", "convex", "data");

// Question set metadata
const QUESTION_SET_METADATA = [
  {
    id: "julebord",
    name: "Julebord Set",
    description: "Norwegian Christmas party questions",
    csvFile: "julebord.csv",
  },
];

// Read CSV files and generate TypeScript
const outputLines: string[] = [
  "// This file is auto-generated from CSV files in convex/data/",
  "// Do not edit this file directly. Edit the CSV files instead.",
  "// Run 'pnpm generate:question-sets' to regenerate this file.",
  "",
  "function parseCSV(csvText: string): Array<{",
  "  category: string;",
  "  text: string;",
  "  answer: string;",
  "  points: number;",
  "}> {",
  "  const lines = csvText.trim().split(\"\\n\");",
  "  const questions = [];",
  "",
  "  for (let i = 1; i < lines.length; i++) {",
  "    const line = lines[i];",
  "    // Simple CSV parser - handles quoted fields",
  "    const values: string[] = [];",
  "    let current = \"\";",
  "    let inQuotes = false;",
  "",
  "    for (let j = 0; j < line.length; j++) {",
  "      const char = line[j];",
  "      if (char === '\"') {",
  "        inQuotes = !inQuotes;",
  "      } else if (char === \",\" && !inQuotes) {",
  "        values.push(current.trim());",
  "        current = \"\";",
  "      } else {",
  "        current += char;",
  "      }",
  "    }",
  "    values.push(current.trim());",
  "",
  "    if (values.length >= 4) {",
  "      questions.push({",
  "        category: values[0],",
  "        text: values[1],",
  "        answer: values[2],",
  "        points: parseInt(values[3], 10),",
  "      });",
  "    }",
  "  }",
  "",
  "  return questions;",
  "}",
  "",
];

// Generate CSV constants and question sets
for (const metadata of QUESTION_SET_METADATA) {
  const csvPath = path.join(dataDir, metadata.csvFile);
  if (!fs.existsSync(csvPath)) {
    console.warn(`Warning: CSV file not found: ${csvPath}`);
    continue;
  }

  const csvContent = fs.readFileSync(csvPath, "utf-8");
  const constantName = metadata.id.toUpperCase().replace(/-/g, "_") + "_CSV";
  
  // Escape the CSV content for TypeScript string literal
  const escapedCsv = csvContent
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\${/g, "\\${");

  outputLines.push(`const ${constantName} = \`${escapedCsv}\`;`);
  outputLines.push("");
}

outputLines.push("export const QUESTION_SETS = [");

for (const metadata of QUESTION_SET_METADATA) {
  const constantName = metadata.id.toUpperCase().replace(/-/g, "_") + "_CSV";
  outputLines.push("  {");
  outputLines.push(`    id: "${metadata.id}",`);
  outputLines.push(`    name: "${metadata.name}",`);
  outputLines.push(`    description: "${metadata.description}",`);
  outputLines.push(`    questions: parseCSV(${constantName}),`);
  outputLines.push("  },");
}

outputLines.push("];");

// Write the generated file
const outputPath = path.join(dataDir, "questionSets.ts");
fs.writeFileSync(outputPath, outputLines.join("\n"), "utf-8");

console.log(`✅ Generated ${outputPath}`);
console.log(`   Processed ${QUESTION_SET_METADATA.length} question set(s)`);
